from django.urls import path
from .views import *
urlpatterns = [
    path('admin-login/', admin_login_api),
    path('add-category/', add_category),
    path('list-categories/', list_categories),
    path('add-food-item/', add_food_item),
    path('foods/', list_foods),
    path('food_search/', food_search),
    path('random_food/', random_food),
    path('register/', register_user),
    path('login/', login_user),
    path('foods/<int:id>/', food_detail),
    path('cart/add/', add_to_cart),
    path('cart/<int:user_id>/', get_cart_items),
    path('cart/update_quantity/', update_cart_quantity),
    path('cart/delete/<int:order_id>/', delete_cart_item),
    path('place_order/', place_order),
    path('orders/<int:user_id>/', user_orders),
    path('orders/by_order_number/<str:order_number>/', order_by_order_number),
    path('orders/order_address/<str:order_number>/', get_order_address),
    path('invoice/<str:order_number>/', get_invoice),
    path('user/<int:user_id>/', get_user_profile),
    path('user/update/<int:user_id>/', update_user_profile),
    path('change_password/<int:user_id>/', change_password),
    path('orders-not-confirmed/', orders_not_confirmed),
    path('orders-confirmed/', orders_confirmed),
    path('food_being_prepared/', food_being_prepared),
    path('foodpickup/', food_pickup),
    path('food-delivered/', food_delivered),
    path('order-cancelled/', order_cancelled),
    path('all-foods/', all_orders),
    path('order-between-dates/', order_between_dates),
    path('view-order-detail/<str:order_number>/', view_order_detail),
    path('update-order-status/', update_order_status),
    path('search-orders/', search_orders),
    path('category-edit-delete/<int:id>/', edit_delete_category),
    path('delete-food/<int:id>/', delete_food),
    path('edit-food/<int:id>/', edit_food),



# api for edit and add food item
#     path('edit-food-item/<int:id>/', edit_food_item),
#     path('get-food-item/<int:id>/', get_food_item),
]
